parameters:
    env(SBO_STAGING_API_USER):  'none'
    env(SBO_STAGING_API_KEY):   'none'

splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
    cache:
        enabled:    true
        lifetime:   3600

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # ShippingBo SandBox
        ShippingBo-SandBox:
            id:                 ThisIsSandBoxWsId
            key:                ThisIsNotASecretKeyForSandBox
            name:               ShippingBo Sandbox
            connector:          shippingbo
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN SHIPPING BO CONTACT
            ########################################################################
            config:
                WsHost:             http://sandbox.shipping-bo.local
                ApiUser:            ThisIsApiUser
                ApiKey:             ThisIsSecretApiKey
                timezone:           UTC
                ShippingMethods:    { "DropShipping": "REJECTED", "Colissimo": "default" }
                OrderOrigins:       { "AllowedWebsite": "pass", "RejectedWebsite": "REJECTED" }
                isSandbox:          true

        ########################################################################
        # ShippingBo Staging
        ShippingBo-Staging:
            id:                 ThisIsStagingWsId
            key:                ThisIsNotASecretKeyForStaging
            name:               ShippingBo Staging
            connector:          shippingbo
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN SHIPPING BO CONTACT
            ########################################################################
            config:
                WsHost:         https://app.shippingbo.com
                ApiUser:        '%env(resolve:SBO_STAGING_API_USER)%'
                ApiKey:         '%env(resolve:SBO_STAGING_API_KEY)%'
                timezone:       'Europe/Paris'

    test:
        VAT: 0
        DoublesPrecision:   1
        PricesPrecision:    2
