################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environnement
# for Splash Optilog Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
#    172.108.0.100       toolkit.shipping-bo.local
#    172.108.0.200       sandbox.shipping-bo.local
#
################################################################################

version: '2.2'

services:
    
    ################################################################################
    # Splash Toolkit Container   
    toolkit:
        image: 'splashsync/toolkit'
        container_name: toolkit.shipping-bo.local
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
            # Uncomment to use Local Sources instead of Release
            - './:/app/vendor/splash/shippingbo/:ro'
            - './tests/Controller:/app/tests/Controller/:ro'
            - './phpunit.xml.dist:/app/phpunit.xml.dist:ro'
        hostname:           toolkit.shipping-bo.local
        networks:
            recommerce:     { ipv4_address: 172.108.0.100, aliases: [ toolkit.shipping-bo.local ] }
            splashsync:     { aliases: [ toolkit.shipping-bo.local ] }

    ################################################################################
    # Splash OpenApi Faker
    openapi:
        image: 'splashsync/openapi-sandbox'
        container_name: sandbox.shipping-bo.local
        volumes:
#             # Specify API Entities to Use
            - './docker/sandbox/Controller:/srv/api/src/Controller:ro'
            - './docker/sandbox/Serializer:/srv/api/src/Serializer:ro'
            - './docker/sandbox/Entity:/srv/api/src/Entity:ro'
            - './docker/sandbox/shippingbo.yml:/srv/api/config/packages/shippingbo.yml:ro'
        hostname:           sandbox.recommerce.local
        networks:
            recommerce:     { ipv4_address: 172.108.0.200, aliases: [ sandbox.shipping-bo.local ] }
            splashsync:     { aliases: [ sandbox.shipping-bo.local ] }

    ################################################################################
    # PHP 8.0
    php-8.0:
        image:          splashsync/php-sdk:php-8.0
        container_name: shipping-bo-8.0
        volumes:
            - ./:/var/www/html
            - vendor-php80:/var/www/html/vendor

    ################################################################################
    # PHP 7.4
    php-7.4:
        image:          splashsync/php-sdk:php-7.4
        container_name: shipping-bo-7.4
        volumes:
            - ./:/var/www/html
            - vendor-php74:/var/www/html/vendor

networks:
    ################################################################################
    # Default Private Network    
    recommerce:
        driver: bridge
        ipam:
            config:
                - subnet: 172.108.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true

volumes:
    vendor-php80: ~
    vendor-php74: ~