api_platform:
    title:  ShippingBo API SandBox
    formats:
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
    swagger:
        api_keys:
            - { name: "X-API-USER", type: "header" }
            - { name: "X-API-TOKEN", type: "header" }
            - { name: "X-API-VERSION", type: "header" }
    collection:
        pagination:
            client_items_per_page: true                     # Disabled by default
            items_per_page_parameter_name: limit            # Default value
            page_parameter_name: offset

    ########################################################################
    # Enable CamelCase To SnakeCase Conversion
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'

services:
    ########################################################################
    # Register CamelCase To SnakeCase Conversion
    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

    ########################################################################
    # ShippingBo Normalizer
    App\Serializer\ApiNormalizer:
        decorates: 'api_platform.serializer.normalizer.item'
        arguments:
            $decorated: '@App\Serializer\ApiNormalizer.inner'