services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ################################################################################
    # SPLASH ShippingBo Connector Service
    splash.connectors.shippingbo:
        class:      Splash\Connectors\ShippingBo\Services\ShippingBoConnector
        bind:
            $metaDir: "%kernel.cache_dir%"
        tags:
            - { name: "splash.connector" }

    ################################################################################
    # Autowire for Services
    Splash\Connectors\ShippingBo\Services\:
        resource:   '../../Services'

    ################################################################################
    # Enables Dependency Injection in Controller Actions
    Splash\Connectors\ShippingBo\Controller\:
        resource:   '../../Controller'
        tags:
            - { name: 'controller.service_arguments' }
